package metamapperbug.model

import _root_.net.liftweb._
import mapper._

class Beeblebrox extends LongKeyedMapper[Beeblebrox] {
  def getSingleton = Beeblebrox
  
  override def primaryKeyField = id
  
  object id extends MappedLongIndex(this) {
    override def dbDisplay_? = true
    override def writePermission_? = true
    override def dbAutogenerated_? = false
    private var myDirty = false
    override def dirty_? = myDirty
    override def dirty_?(b : Boolean) = { myDirty = b; super.dirty_?(b) }
  }
  
  object answer extends MappedPoliteString(this, 42) {
    override def defaultValue = "forty two"
  }
}

object Beeblebrox extends Beeblebrox with LongKeyedMetaMapper[Beeblebrox]